name: Test
on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TASK_NAME: '🔧'
          TZ: 'Asia/Tokyo'
  test-with:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TASK_NAME: '🔧'
          TZ: 'Asia/Tokyo'
